idf_component_register(
    SRCS "gui_service.c"
         "page_manager.c"
         "gui_actions.c"
         "theme/kdl_theme.c"
         "channels/kdl_channels.c"
         "assets/kdl_splash.c"
         "assets/fonts/kdl_font_text_10.c"
         "assets/fonts/kdl_font_text_12.c"
         "assets/fonts/kdl_font_text_14.c"
         "assets/fonts/kdl_font_text_20.c"
         "assets/fonts/kdl_font_num_16.c"
         "assets/fonts/kdl_font_num_22.c"
         "assets/fonts/kdl_font_num_26.c"
         "assets/fonts/kdl_font_num_32.c"
         "widgets/kdl_widgets.c"
         "pages/page_splash.c"
         "pages/page_main.c"
         "pages/page_graph.c"
         "pages/page_settings.c"
         "pages/page_datetime.c"
         "pages/page_usb.c"
    INCLUDE_DIRS "include"
    PRIV_INCLUDE_DIRS "."
    EMBED_FILES "assets/splash_480x320_rgb565.bin"
    REQUIRES display data_model acquisition logger storage usb_msc digital_inputs board timekeeping settings lvgl
)
