#pragma once

#include "lvgl.h"

/**
 * @file kdl_theme.h
 * @brief Design tokens (palette, fonts, shared styles) for the KDatalogger UI.
 *
 * The UI is a flat, high-contrast instrument panel: no shadows, no
 * gradients. Every surface is a solid fill delimited by 1 px strokes, which
 * keeps the invalidated areas small and the SPI flush cheap. Corners are
 * rounded by 3-4 px on containers only: those are redrawn only when a child
 * inside them changes, and the anti-aliased corner arcs fall outside the
 * small areas a value update invalidates. Do not introduce shadow or
 * gradient styles here without re-checking the refresh budget in
 * display_driver.c.
 */

/* -- Palette ---------------------------------------------------------------
 * Hex values are the single source of truth for the whole GUI; pages and
 * widgets must reference these macros, never a literal lv_color_hex().      */

#define KDL_COLOR_INK           lv_color_hex(0x14161A)  /**< Primary text / strokes  */
#define KDL_COLOR_INK_DIM       lv_color_hex(0x4A4E55)  /**< Secondary values        */
#define KDL_COLOR_INK_MUTED     lv_color_hex(0x6B6F76)  /**< Units, ids, captions    */
#define KDL_COLOR_INK_FAINT     lv_color_hex(0x8D9198)  /**< Micro labels            */

#define KDL_COLOR_PAPER         lv_color_hex(0xF4F3EF)  /**< Screen background       */
#define KDL_COLOR_CARD          lv_color_hex(0xFFFFFF)  /**< Tile and key cap fill   */
#define KDL_COLOR_SURFACE       lv_color_hex(0xECEAE3)  /**< Analog cells, panels    */
#define KDL_COLOR_RAIL          lv_color_hex(0xE9E7E1)  /**< Key label rail          */

#define KDL_COLOR_BORDER        lv_color_hex(0xD5D3CC)  /**< Idle row border         */
#define KDL_COLOR_BORDER_SOFT   lv_color_hex(0xC9C7C0)  /**< Legend cell border      */
#define KDL_COLOR_HAIRLINE      lv_color_hex(0xECEAE3)  /**< In-card separator       */
#define KDL_COLOR_TRACK         lv_color_hex(0xE3E1DA)  /**< Fill-bar track          */

#define KDL_COLOR_HOT           lv_color_hex(0xC8481F)  /**< Over high threshold     */
#define KDL_COLOR_WARM          lv_color_hex(0xB57614)  /**< Approaching threshold   */

#define KDL_COLOR_TINT_HOT      lv_color_hex(0xFDEEE8)  /**< Tile fill in alarm      */
#define KDL_COLOR_TINT_WARM     lv_color_hex(0xFBF3E4)  /**< Tile fill in warning    */
#define KDL_COLOR_BORDER_WARM   lv_color_hex(0xD9B679)  /**< Tile border in warning  */

#define KDL_COLOR_ZONE_OK       lv_color_hex(0xE6E4DD)  /**< Track below warning     */
#define KDL_COLOR_ZONE_WARM     lv_color_hex(0xF1D9A8)  /**< Track, warning band     */
#define KDL_COLOR_ZONE_HOT      lv_color_hex(0xF3C2AF)  /**< Track, alarm band       */

#define KDL_COLOR_STATUS_CAPTION lv_color_hex(0xB9B7B0) /**< Title on the status bar */

#define KDL_COLOR_REC_ON        lv_color_hex(0xFF4B2B)  /**< REC dot, lit phase      */
#define KDL_COLOR_REC_OFF       lv_color_hex(0x7A1D10)  /**< REC dot, dark phase     */
#define KDL_COLOR_REC_STOPPED   lv_color_hex(0x8D9198)  /**< REC dot while stopped   */

#define KDL_COLOR_ALERT_BG      lv_color_hex(0xFDEEE8)
#define KDL_COLOR_ALERT_BORDER  lv_color_hex(0xC8481F)
#define KDL_COLOR_ALERT_INK     lv_color_hex(0x7A2B12)

#define KDL_COLOR_KEY_BORDER    lv_color_hex(0xCFCDC6)  /**< Key cap outline         */

/** @brief Number of distinct chart series colours available. */
#define KDL_SERIES_COLOR_COUNT 6

/* -- Fonts -----------------------------------------------------------------
 * Generated by tools/gen_fonts.py from Barlow (OFL, tools/fonts/):
 *
 *  kdl_font_text_*  Barlow SemiBold -- ASCII, the Italian accented vowels,
 *                   ° · • Δ — and the LV_SYMBOL_* glyphs listed in the script.
 *  kdl_font_num_*   Barlow Condensed SemiBold -- digits, "- . :", space, the
 *                   letters of the fault codes (SCG, SCV, ERR) and the em dash
 *                   only. Digits are tabular, so a changing reading does not
 *                   shift sideways.
 *
 * Any other character renders as nothing: add it to the ranges in
 * tools/gen_fonts.py and regenerate. Line heights are the tight bounding box
 * of the glyphs included (a num face is exactly as tall as its digits), so
 * label heights below are sized against those, not against the point size. */

LV_FONT_DECLARE(kdl_font_text_10)
LV_FONT_DECLARE(kdl_font_text_12)
LV_FONT_DECLARE(kdl_font_text_14)
LV_FONT_DECLARE(kdl_font_text_20)
LV_FONT_DECLARE(kdl_font_num_16)
LV_FONT_DECLARE(kdl_font_num_22)
LV_FONT_DECLARE(kdl_font_num_26)
LV_FONT_DECLARE(kdl_font_num_32)

#define KDL_FONT_MICRO    (&kdl_font_text_10) /**< Captions, min/max, date     */
#define KDL_FONT_BODY     (&kdl_font_text_12) /**< Status bar, lists, hints    */
#define KDL_FONT_KEY      (&kdl_font_text_14) /**< Key labels, tile names      */
#define KDL_FONT_TITLE    (&kdl_font_text_20) /**< Page headings               */
#define KDL_FONT_NUM_S    (&kdl_font_num_16)  /**< Elapsed time, spread        */
#define KDL_FONT_NUM_M    (&kdl_font_num_22)  /**< Cylinder readings, clock    */
#define KDL_FONT_NUM_L    (&kdl_font_num_26)  /**< Analog readings             */
#define KDL_FONT_NUM_XL   (&kdl_font_num_32)  /**< Tile readings, date entry   */

/* -- Shared styles ---------------------------------------------------------
 * Owned by kdl_theme.c and valid for the lifetime of the program. Pages
 * attach them with lv_obj_add_style(); they must never be modified in place
 * by a page, since every widget using them would change at once.            */

extern lv_style_t kdl_style_screen;      /**< Root screen fill                  */
extern lv_style_t kdl_style_statusbar;   /**< Inverted top bar                  */
extern lv_style_t kdl_style_panel;       /**< Bare container: no pad/border/bg  */
extern lv_style_t kdl_style_tile;        /**< White readout tile, soft border   */
extern lv_style_t kdl_style_rail;        /**< Key label rail                    */
extern lv_style_t kdl_style_keycap;      /**< Labelled key on the rail          */
extern lv_style_t kdl_style_row;         /**< Settings row, idle                */
extern lv_style_t kdl_style_row_sel;     /**< Settings row, selected (inverted) */
extern lv_style_t kdl_style_alert;       /**< Warning banner                    */

/**
 * @brief Build the shared styles. Call once, before any page is created,
 *        with the LVGL context locked.
 */
void kdl_theme_init(void);

/**
 * @brief Apply the screen-level background and clear the default padding.
 *
 * @param screen Active screen object.
 */
void kdl_theme_apply_screen(lv_obj_t *screen);

/**
 * @brief Colour for chart series @p index, wrapping at KDL_SERIES_COLOR_COUNT.
 */
lv_color_t kdl_theme_series_color(uint8_t index);
